#!/bin/sh

mvn clean package shade:shade -DskipTests

find /media/disk6TV1/ali/larger-dataset/*/ -wholename */buggy-version/*.java | awk 'BEGIN{FS="/"} {print $0",/"$2"/"$3"/"$4"/"$5"/"$6"/"$7"/"$8"/fixed-version/"$10}' | java -cp target/fix-pattern-miner-1.0.0-SNAPSHOT.jar Main -c -p -s /media/disk6TV1/ali/larger-dataset/serialized-rules.gz
