#!/bin/bash

mvn clean package shade:shade -DskipTests

find /home/ali/hdrepair-dataset -wholename */old/*.java | awk 'BEGIN{FS="/"} {print $0",/"$2"/"$3"/"$4"/"$5"/"$6"/"$7"/fix/"$9}' | java -cp target/fix-pattern-miner-1.0.0-SNAPSHOT.jar edu.utdallas.fpm.main.Main -p

