#!/bin/sh

mvn clean package shade:shade -DskipTests

find hdrepair-dataset -wholename */old/*.java | awk 'BEGIN{FS="/"} {print $0",/"$2"/"$3"/"$4"/"$5"/"$6"/"$7"/"$8"/fix/"$10}' | java -cp target/fix-pattern-miner-1.0.0-SNAPSHOT.jar edu.utdalls.fpm.main.Main -p -m pppp
